export const ACTIONS_TYPE = {
	SET_TASK: "SET_TASK",
	SET_TASKS: "SET_TASKS",
	SET_LOADING: "SET_LOADING",
	CREATE_TASK: "CREATE_TASK",
	UPDATE_TASK: "UPDATE_TASK",
	DELETE_TASK: "DELETE_TASK",
	SET_VALUE_INPUT: "SET_VALUE_INPUT",
	SET_IS_LOADING: "SET_IS_LOADING",
	SET_IS_SORTED: "SET_IS_SORTED"
}